development:
    checkout_url: http://localhost:4000/integration_requests
    ipn_url: http://localhost:4000/queries
staging:
    checkout_url: http://localhost:4000/integration_requests
    ipn_url: http://localhost:4000/queries
production:
    checkout_url: https://chile.dineromail.com/Vender/ConsultaPago.asp
    ipn_url: https://chile.dineromail.com/Vender/ConsultaPago.asp